name: Deploy

on:
  push:
    branches: [main]
    paths:
      - "api/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          clean: false

      - name: test
        working-directory: ./api
        run: ls

      - name: Install the dependencies
        working-directory: ./api
        run: go get

      - name: Prisma
        working-directory: ./api/prisma
        run: go run github.com/prisma/prisma-client-go db push

      - name: Build
        run: cd api && go build

      - name: Restart PMGO
        run: pmgo restart HITS-PROD
